# -*- coding: utf-8 -*-
"""projectk4_pynb (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_6SE47OyiVDk8pUP6uY9jNfsRk7uVaQ
"""

import pandas as pd
import networkx as nx

df = pd.read_json("/content/careers_dataset_50plus.json")

df.head()

# ensure lists are lists
def fix_list(x):
    if isinstance(x, list):
        return x
    if pd.isna(x):
        return []
    return [s.strip() for s in str(x).split(",")]

df["required_skills"] = df["required_skills"].apply(fix_list)
df["recommended_courses"] = df["recommended_courses"].apply(fix_list)
df["projects"] = df["projects"].apply(fix_list)

G = nx.Graph()

# Add career nodes
for _, row in df.iterrows():
    G.add_node(row["career_name"], type="career")

    for skill in row["required_skills"]:
        G.add_node(skill.lower(), type="skill")
        G.add_edge(row["career_name"], skill.lower(), weight=2)

    for course in row["recommended_courses"]:
        G.add_node(course.lower(), type="course")
        G.add_edge(row["career_name"], course.lower(), weight=1)

    for proj in row["projects"]:
        G.add_node(proj.lower(), type="project")
        G.add_edge(row["career_name"], proj.lower(), weight=1)

user_name = input("Enter your name: ")
user_branch = input("Enter your branch (CSE/ECE/MECH/etc): ")
user_skills = input("Enter your skills (comma separated): ").lower().split(",")
user_interests = input("Enter your interests (comma separated): ").lower().split(",")

# Add the user node
G.add_node(user_name, type="user")

# Add edges (user → skills)
for s in user_skills:
    s = s.strip()
    G.add_node(s, type="skill")
    G.add_edge(user_name, s, weight=3)

# Add edges (user → interests)
for i in user_interests:
    i = i.strip()
    G.add_node(i, type="interest")
    G.add_edge(user_name, i, weight=2)

def recommend_graph(user_name, top_k=5):
    scores = []

    # iterate over all careers
    for _, row in df.iterrows():
        career = row["career_name"]

        # compute common neighbors between user and career
        common = list(nx.common_neighbors(G, user_name, career))

        score = 0
        for node in common:
            edge_user = G[user_name][node]["weight"]
            edge_career = G[career][node]["weight"]
            score += edge_user + edge_career

        scores.append((career, score))

    # sort scores
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    return scores[:top_k]

def print_results(results):
    for idx, (career, score) in enumerate(results, start=1):
        row = df[df["career_name"] == career].iloc[0]

        print(f"\n{idx}. {career}  (score: {score})")
        print(f"   required_skills: {row['required_skills'][:5]}")
        print(f"   recommended_courses: {row['recommended_courses'][:3]}")
        print(f"   roadmap: {row['roadmap']}\n")

results = recommend_graph(user_name, top_k=5)
print_results(results)

