# -*- coding: utf-8 -*-
"""tfidf_career_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sRWOFQq1qvn4PFwLlgGF6-ZwsgnFCI1B

# TF-IDF Career Recommendation System

This notebook implements a career recommendation system using **TF-IDF (Term Frequency-Inverse Document Frequency)** and cosine similarity.

## Step 1: Import Required Libraries
"""

import json
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("✅ Libraries imported successfully!")

"""## Step 2: Load Career Dataset"""

# Load careers dataset
with open("careers_dataset_50plus.json", "r") as f:
    careers_data = json.load(f)

print(f"✅ Loaded {len(careers_data)} careers from dataset")
print(f"\nSample career: {careers_data[0]['career_name']}")

"""## Step 3: Prepare Career Data"""

def safe_list_to_string(data):
    """Convert list or string to clean string format"""
    if isinstance(data, list):
        return " ".join([str(item) for item in data if item])
    elif isinstance(data, str):
        return data
    else:
        return ""

# Create DataFrame
careers_df = pd.DataFrame(careers_data)

# Combine all text fields for each career
def combine_career_text(row):
    parts = []
    parts.append(str(row.get('career_name', '')))
    parts.append(str(row.get('category', '')))
    parts.append(safe_list_to_string(row.get('required_skills', [])))
    parts.append(safe_list_to_string(row.get('recommended_courses', [])))
    parts.append(safe_list_to_string(row.get('projects', [])))
    parts.append(str(row.get('roadmap', '')))
    return " ".join([p for p in parts if p])

careers_df['combined_text'] = careers_df.apply(combine_career_text, axis=1)

print(f"✅ Prepared {len(careers_df)} career profiles")
print(f"\nFirst career combined text preview:")
print(careers_df['combined_text'].iloc[0][:200] + "...")

"""## Step 4: Build TF-IDF Model"""

# Initialize TF-IDF Vectorizer
tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=5000,
    ngram_range=(1, 2),  # Use both unigrams and bigrams
    min_df=1
)

# Fit and transform career texts
tfidf_matrix = tfidf.fit_transform(careers_df['combined_text'])

print(f"✅ TF-IDF matrix created: {tfidf_matrix.shape}")
print(f"   - {tfidf_matrix.shape[0]} careers")
print(f"   - {tfidf_matrix.shape[1]} features (terms)")

"""## Step 5: Define Recommendation Function"""

def recommend_careers_tfidf(user_profile, top_k=5):
    """
    Recommend careers based on user profile using TF-IDF + Cosine Similarity

    Args:
        user_profile (dict): User's profile containing skills, interests, etc.
        top_k (int): Number of recommendations to return

    Returns:
        list: Top K recommended careers with scores
    """
    # Combine user profile into text
    user_text_parts = []
    user_text_parts.append(user_profile.get('department', ''))
    user_text_parts.append(user_profile.get('interests', ''))
    user_text_parts.append(' '.join(user_profile.get('skills', [])))
    user_text_parts.append(' '.join(user_profile.get('projects', [])))
    user_text_parts.append(' '.join(user_profile.get('certifications', [])))

    user_text = ' '.join([p for p in user_text_parts if p])

    print(f"\n🔍 User Profile Text:\n{user_text}\n")

    # Transform user text using the trained TF-IDF vectorizer
    user_vector = tfidf.transform([user_text])

    # Calculate cosine similarity
    similarities = cosine_similarity(user_vector, tfidf_matrix)[0]

    # Get top K indices
    top_indices = similarities.argsort()[-top_k:][::-1]

    # Prepare results
    recommendations = []
    for idx in top_indices:
        career = careers_data[idx]
        recommendations.append({
            'career_name': career['career_name'],
            'category': career.get('category', 'N/A'),
            'similarity_score': float(similarities[idx]),
            'required_skills': career.get('required_skills', []),
            'recommended_courses': career.get('recommended_courses', []),
            'roadmap': career.get('roadmap', 'N/A')
        })

    return recommendations

print("✅ Recommendation function defined")

"""## Step 6: Get User Input"""

# Collect user input
print("\n" + "="*60)
print("       WELCOME TO TF-IDF CAREER RECOMMENDER SYSTEM")
print("="*60 + "\n")

name = input("Enter your name: ").strip()
department = input("Enter your department (e.g., CSE, ECE, MECH): ").strip()
skills_input = input("Enter your skills (comma-separated): ").strip()
interests = input("Enter your career interests: ").strip()
projects_input = input("Enter your projects (comma-separated): ").strip()
certifications_input = input("Enter your certifications (comma-separated): ").strip()

# Parse inputs
skills = [s.strip() for s in skills_input.split(',') if s.strip()]
projects = [p.strip() for p in projects_input.split(',') if p.strip()]
certifications = [c.strip() for c in certifications_input.split(',') if c.strip()]

# Create user profile
user_profile = {
    'name': name,
    'department': department,
    'skills': skills,
    'interests': interests,
    'projects': projects,
    'certifications': certifications
}

print("\n✅ Profile created successfully!")

"""## Step 7: Generate Recommendations"""

# Get recommendations
print("\n" + "="*60)
print(f"  CAREER RECOMMENDATIONS FOR {user_profile['name'].upper()}")
print("="*60)

recommendations = recommend_careers_tfidf(user_profile, top_k=5)

# Display recommendations
print(f"\n🎯 Top 5 Career Recommendations (TF-IDF Method):\n")

for i, rec in enumerate(recommendations, 1):
    print(f"\n{'='*60}")
    print(f"Rank #{i}: {rec['career_name']}")
    print(f"{'='*60}")
    print(f"📊 Similarity Score: {rec['similarity_score']:.4f}")
    print(f"📁 Category: {rec['category']}")
    print(f"\n💡 Required Skills:")
    for skill in rec['required_skills'][:5]:  # Show top 5 skills
        print(f"   • {skill}")
    print(f"\n📚 Recommended Courses:")
    for course in rec['recommended_courses'][:3]:  # Show top 3 courses
        print(f"   • {course}")
    print(f"\n🗺️ Career Roadmap:")
    print(f"   {rec['roadmap'][:150]}..." if len(rec['roadmap']) > 150 else f"   {rec['roadmap']}")

print("\n" + "="*60)
print("           RECOMMENDATIONS COMPLETE!")
print("="*60)

"""## Step 8: Visualize Results (Optional)"""

import matplotlib.pyplot as plt

# Extract data for visualization
career_names = [rec['career_name'] for rec in recommendations]
scores = [rec['similarity_score'] for rec in recommendations]

# Create bar plot
plt.figure(figsize=(10, 6))
plt.barh(career_names, scores, color='steelblue')
plt.xlabel('Similarity Score', fontsize=12)
plt.ylabel('Career', fontsize=12)
plt.title(f'Top 5 Career Recommendations for {user_profile["name"]} (TF-IDF)', fontsize=14, fontweight='bold')
plt.gca().invert_yaxis()
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

print("✅ Visualization complete!")

